# Generated by Django 3.2.20 on 2023-09-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cvbgh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vbfd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ytut', models.BigIntegerField()),
                ('hhfj', models.BigIntegerField()),
            ],
        ),
    ]
